apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}-headless
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: {{ .Values.image }}
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.MYSQL_ROOT_PASSWORD }}
            - name: MYSQL_DATABASE
              value: {{ .Values.MYSQL_DATABASE }}
            - name: MYSQL_USER
              value: {{ .Values.MYSQL_USER }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.MYSQL_PASSWORD }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
