apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
            - name: DOMAIN
              value: https://{{ .Values.host }}
          {{ if .Values.ADMIN_TOKEN }}
            - name: ADMIN_TOKEN
              value: {{ .Values.ADMIN_TOKEN }}
          {{ end }}
          {{ if .Values.SSO_ENABLED }}
            - name: SSO_ENABLED
              value: {{ .Values.SSO_ENABLED | quote }}
          {{ end }}
          {{ if .Values.SSO_ONLY }}
            - name: SSO_ONLY
              value: {{ .Values.SSO_ONLY | quote }}
          {{ end }}
          {{ if .Values.SSO_AUTHORITY }}
            - name: SSO_AUTHORITY
              value: {{ .Values.SSO_AUTHORITY | quote }}
          {{ end }}
          {{ if .Values.SSO_CLIENT_ID }}
            - name: SSO_CLIENT_ID
              value: {{ .Values.SSO_CLIENT_ID | quote }}
          {{ end }}
          {{ if .Values.SSO_CLIENT_SECRET }}
            - name: SSO_CLIENT_SECRET
              value: {{ .Values.SSO_CLIENT_SECRET | quote }}
          {{ end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: data
              mountPath: /data
