apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    {{- range $k, $v := .Values.ingressExtraAnnotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Release.Name }}-tls
  rules:
    - host: {{ required ".Values.host is required" .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
