{{- range $certificate := .Values.certificates }}
{{- range $targetNamespace := $certificate.targetNamespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $certificate.name }}
  namespace: {{ $targetNamespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $certificate.tlsCrtBase64 }}
  tls.key: {{ $certificate.tlsKeyBase64 }}
{{- end }}
{{- end }}
