{{- range $clusterIssuer := .Values.clusterIssuersLetsencrypt }}
kind: ClusterIssuer
metadata:
  name: {{ $clusterIssuer.name }}
spec:
  acme:
    email: {{ $clusterIssuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ $clusterIssuer.name }}-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
{{- end }}
