apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- if not .Values.tls.enabled }}
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
    {{- end }}

    {{- if .Values.tls.enabled }}
    - protocol: TCP
      port: 443
      targetPort: https
      name: https
    {{- end }}
  selector:
    app: {{ .Release.Name }}
