apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name }}
spec:
  type: filebeat
  version: 8.12.0
  elasticsearchRef:
    name: {{ .Values.elasticsearchRef | quote }}
  daemonSet:
    podTemplate:
      spec:
        serviceAccount: {{ .Release.Name }}
        automountServiceAccountToken: true
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
  config:
    output:
      logstash:
        hosts: ['{{ required ".Values.LOGSTASH_HOST is required" .Values.LOGSTASH_HOST }}:5044']
    filebeat:
      autodiscover:
        providers:
        - host: ${NODE_NAME}
          type: kubernetes
          hints:
            enabled: true
            default_config:
              type: container
              paths:
                - /var/log/containers/*${data.kubernetes.container.id}.log
