apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: postgres
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: postgres
    spec:
      containers:
        - name: main
          image: {{ required ".Values.image is required" .Values.image }}
          ports:
           - containerPort: 5432
          env:
           - name: POSTGRES_PASSWORD
             value: "{{ required ".Values.POSTGRES_PASSWORD is required" .Values.POSTGRES_PASSWORD}}"
           - name: PGDATA
             value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
           - name: postgres
             mountPath: "/var/lib/postgresql/data"
  volumeClaimTemplates:
    - metadata:
       name: postgres
      spec:
       accessModes:
       - ReadWriteOnce
       {{- if .Values.storageClassName }}
       storageClassName: {{ .Values.storageClassName }}
       {{- end }}
       resources:
        requests:
         storage: {{ .Values.storageSize }}

