{{- if .Values.additionalConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-configs-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
type: Opaque
data:
{{- range .Values.additionalConfigs }}
  {{ .name }}: {{ .config | b64enc }}
{{- end }}
{{- end }}