{{- range .Values.rbacRules }}
{{- if and .rules .clusterWide .namespaces }}
{{- $rule := . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name }}
rules:
  {{- range .rules }}
  - apiGroups:
      {{- range .apiGroups }}
      - {{ . | quote }}
      {{- end }}
    resources:
      {{- range .resources }}
      - {{ . | quote }}
      {{- end }}
    verbs:
      {{- range .verbs }}
      - {{ . | quote }}
      {{- end }}
  {{- end }}
{{- range .namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $rule.name }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $rule.name }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $rule.group }}
{{- end }}
{{- else if and .rules .clusterWide }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name }}
rules:
  {{- range .rules }}
  - apiGroups:
      {{- range .apiGroups }}
      - {{ . | quote }}
      {{- end }}
    resources:
      {{- range .resources }}
      - {{ . | quote }}
      {{- end }}
    verbs:
      {{- range .verbs }}
      - {{ . | quote }}
      {{- end }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .name }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ .group }}
{{- else if and .rules .namespaces }}
{{- $rule := . }}
{{- range .namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $rule.name }}
  namespace: {{ . }}
rules:
  {{- range $rule.rules }}
  - apiGroups:
      {{- range .apiGroups }}
      - {{ . | quote }}
      {{- end }}
    resources:
      {{- range .resources }}
      - {{ . | quote }}
      {{- end }}
    verbs:
      {{- range .verbs }}
      - {{ . | quote }}
      {{- end }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $rule.name }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $rule.name }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $rule.group }}
{{- end }}
{{- else if and .existingClusterRole .clusterWide }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .existingClusterRole }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ .group }}
{{- else if and .existingClusterRole .namespaces }}
{{- $rule := . }}
{{- range .namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $rule.name }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $rule.existingClusterRole }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $rule.group }}
{{- end }}
{{- else if and .existingRole .namespaces }}
{{- $rule := . }}
{{- range .namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $rule.name }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $rule.existingRole }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $rule.group }}
{{- end }}
{{- end }}
{{- end }}
