apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-install-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-install-cr
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-install-crb
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-install-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-install-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-job
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-install-sa
      containers:
        - name: kubectl-exec
          image: bitnami/kubectl
          command:
            - sh
            - -c
            - |
              kubectl apply -f /tmp/olm.yaml
          volumeMounts:
            - name: {{ .Release.Name }}-config
              mountPath: /tmp
      volumes:
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}-config
      restartPolicy: Never
