rbacRules:
  # Custom ClusterRole (cluster-wide)
  #- name: admin-role
  #  group: kubernetes-admin
  #  clusterWide: true
  #  rules:
  #    - apiGroups: ["*"]
  #      resources: ["*"]
  #      verbs: ["*"]

  # Custom ClusterRole bound in specific namespaces
  #- name: ch-devs-extensions
  #  group: "k8s:devs"
  #  clusterWide: true
  #  namespaces: [ch-kong, ch-camunda-orch]
  #  rules:
  #    - apiGroups: ["gateway.networking.k8s.io"]
  #      resources: ["httproutes"]
  #      verbs: ["*"]

  # Custom Role in multiple namespaces
  #- name: pod-reader
  #  group: kubernetes-dev
  #  namespaces: [default, monitoring]
  #  rules:
  #    - apiGroups: [""]
  #      resources: [pods]
  #      verbs: [get, list, watch]

  # Bind to existing ClusterRole cluster-wide
  #- name: view-all-binding
  #  group: kubernetes-viewer
  #  existingClusterRole: view
  #  clusterWide: true

  # Bind to existing ClusterRole in specific namespaces
  #- name: dev-edit-binding
  #  group: kubernetes-dev
  #  existingClusterRole: edit
  #  namespaces: [default, staging]

  # Bind to existing Role in specific namespaces
  #- name: dev-custom-binding
  #  group: kubernetes-dev
  #  existingRole: my-custom-role
  #  namespaces: [default]
