{{ if and (.Values.authUser) (.Values.authPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ingress-auth
  labels:
    release: {{ .Release.Name }}
stringData:
  auth: {{ htpasswd .Values.authUser .Values.authPassword }}
{{ end }}
