apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-http
  labels:
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    release: {{ .Release.Name }}
