apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}{{ .Release.Name }}
  labels:
    release: {{ .Values.namePrefix }}{{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    release: {{ .Values.namePrefix }}{{ .Release.Name }}
