apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: api
      targetPort: api
    - port: 8080
      name: console
      targetPort: console
  selector:
    release: {{ .Release.Name }}
