# Required
host:
homeserver:

# Optional
clusterIssuer: letsencrypt
# ingressExtraAnnotations:
#   name: value
#   foo: bar
ingressClassName: nginx
ingressExtraAnnotations: {}
tlsKeyBase64: null
tlsCrtBase64: null
