apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{ if .Values.wwwRedirect }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    {{ end }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.host }}-tls
    {{ if .Values.wwwRedirect }}
    - hosts:
        - www.{{ .Values.host }}
      secretName: www.{{ .Values.host }}-tls
    {{ end }}
  rules:
    - host: {{ required ".Values.host is required" .Values.host }}
      http:
        paths:
          - path: {{ .Values.path }}
            pathType: {{ .Values.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
