{{ if and (.Values.tlsKeyBase64 ) (.Values.tlsCrtBase64 ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
type: kubernetes.io/tls
data:
  tls.key: {{ .Values.tlsKeyBase64 }}
  tls.crt: {{ .Values.tlsCrtBase64 }}
{{ end }}
