apiVersion: v2
description: Scheduled App Helm Chart for running scheduled tasks
icon: https://avatars.githubusercontent.com/u/16311959?s=200&v=4
type: application
maintainers:
  - name: jozefvojtek
    email: jozef.vojtek@sikalabs.com
name: scheduled-app
version: 0.1.0
