image:
  repository: ""
  tag: ""
  pullSecretName: ""

resources:
  requests:
    memory: 10Mi
    cpu: 25m
  limits:
    memory: 50Mi
    cpu: 50m

concurrencyPolicy: "Forbid"

cron: "*/5 * * * *"

# Example:
## commands:
##  - echo "Hello World!"
commands: []

# Used to create a Secret with additional configuration files for the container
# Example:
## additionalConfigs:
##   - name: "config.yaml"
##     mountPath: "/app"
##     config: |
##       dbConfig:
##         key: value
##       httpConfig:
##         key: value
additionalConfigs: []

# Used to mount an existing secrets containing additional configuration files to the container
# Example:
## existingConfigs:
##   - secretName: "my-secret"
##     name: "config.yaml"
##     mountPath: "/app"
existingConfigs: []


# Used to add additional annotations to the pod
# Example:
## additionalPodAnnotations:
##   prometheus.io/scrape: "true"
##   prometheus.io/port: "8080"
additionalPodAnnotations: {}

# Used to add additional volume mounts to the container
## Example:
## volumeMounts:
##   - name: "my-volume"
##     mountPath: "/data"
volumeMounts: []

# Used to add additional volumes to the pod
# Example:
## volumes:
##   - name: "my-volume"
##     persistentVolumeClaim:
##       claimName: "my-pvc"
##   - name: "my-secret-volume"
##     secret:
#         secretName: "my-secret"
##    - name: "my-emptydir-volume"
##      emptyDir: {}
volumes: []

# Used to add init containers to the pod
## Example:
## initContainers:
##   - name: "init-myservice"
##     image:
##       repository: "my-init-image"
##       tag: "latest"
##     commands:
##       - "echo 'Initializing...'"
##     resources:
##       requests:
##         memory: 20Mi
##         cpu: 50m
##       limits:
##         memory: 50Mi
##         cpu: 100m
##     volumeMounts:
##      - name: "my-volume"
##        mountPath: "/data"
initContainers: []
