{{ $includedNamespaces := .Values.includedNamespaces }}
{{ $excludedNamespaces := .Values.excludedNamespaces }}
{{- range $trustMount := .Values.trustMounts }}
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: {{ $trustMount.name }}-volume-mount
spec:
  applyTo:
    - groups: [ "" ]
      kinds: [ "Pod" ]
      versions: [ "v1" ]
  match:
    scope: Namespaced
    kinds:
      - apiGroups: [ "*" ]
        kinds: [ "Pod" ]
    {{- if $includedNamespaces }}
    namespaces:
      {{- range $includedNamespace := .Values.includedNamespaces }}
      - {{ $includedNamespace | quote }}
      {{- end }}
    {{- end}}
    {{- if $excludedNamespaces }}
    excludedNamespaces:
      {{- range $excludedNamespace := $excludedNamespaces }}
      - {{ $excludedNamespace | quote }}
      {{- end }}
    {{- end }}
  location: "spec.containers[name:*].volumeMounts[name:{{ $trustMount.name }}]"
  parameters:
    assign:
      value:
        mountPath: {{ $trustMount.path }}
        name: {{ $trustMount.name }}
        readOnly: true
---
{{- end }}
