apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: {{ .Release.Name }}-bundle
spec:
  sources:
    - useDefaultCAs: {{ .Values.usePublicCAs }}
{{- if .Values.customCAs }}
    - inLine: |
{{ .Values.customCAs | indent 8 }}
{{- end }}
  target:
    configMap:
      key: "ca-bundle.crt"
    namespaceSelector:
    {{- if .Values.includedNamespaces }}
      matchNames:
      {{- range $includedNamespace := .Values.includedNamespaces }}
        - {{ $includedNamespace | quote }}
      {{- end }}
    {{- end }}
