apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.port }}
      nodePort: {{ .Values.nodePort }}
  selector:
    release: {{ .Release.Name }}
