apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}

  annotations:
    {{ if .Values.wwwRedirect }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    {{ end }}
    {{ if .Values.tls }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    {{ end }}
    {{ if and (.Values.basicAuth.username) (.Values.basicAuth.password)  }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Release.Name }}-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{ end }}
    {{- range $k, $v := .Values.ingressExtraAnnotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  {{ if .Values.tls }}
  tls:
    - hosts:
        - {{ .Values.host }}
        {{ if .Values.wwwRedirect }}
        - www.{{ .Values.host }}
        {{ end }}
      secretName: {{ .Release.Name }}-tls
  {{ end }}
  rules:
    - host: {{ required ".Values.host is required" .Values.host }}
      http:
        paths:
          - path: {{ .Values.path }}
            pathType: {{ .Values.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
