# Required
host:

# Optional
clusterIssuer: letsencrypt
smtpServiceType: ClusterIP
smtpNodePort:
authUser:
authPassword:
ingressExtraAnnotations: {}
# ingressExtraAnnotations:
#   name: value
#   foo: bar
