# Required
schedule:
extraName:
tergumConfig:

# Optional
image: sikalabs/tergum:v0.40.0
useV2: false
mountRootPath: false
existingSecret: null
expandEnv: false
mountPVCName: null
affinitySameNodeKey: null
affinitySameNodeValue: null
customCASecret: null
